--- # api_gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-api-gateway
  namespace: sas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sas-api_gateway
  template:
    metadata:
      labels:
        app: sas-api_gateway
    spec:
      containers:
        - name: api-gateway
          image: registry.msvacina.cz/sas-api_gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: RUST_LOG
              value: "info"
            - name: SAS_PORT
              value: "8080"
            - name: NATS_URL
              value: "192.168.1.211:4222"
            - name: REQUESTS_MAX_MESSAGES
              value: "1000"

---
apiVersion: v1
kind: Service
metadata:
  name: sas-api-service
  namespace: sas
spec:
  type: LoadBalancer
  selector:
    app: sas-api_gateway
  ports:
    - port: 8080
      targetPort: 8080

--- # data_persistor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-data-persistor
  namespace: sas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sas-data-persistor
  template:
    metadata:
      labels:
        app: sas-data-persistor
    spec:
      containers:
        - name: data-persistor
          image: registry.msvacina.cz/sas-data_persistor:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: "info"
            - name: NATS_URL
              value: "192.168.1.211:4222"
            - name: REQUESTS_MAX_MESSAGES
              value: "1000"

--- # shorts_service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-shorts-service
  namespace: sas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sas-shorts-service
  template:
    metadata:
      labels:
        app: sas-shorts-service
    spec:
      containers:
        - name: shorts-service
          image: registry.msvacina.cz/sas-shorts_service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: "info"
            - name: NATS_URL
              value: "192.168.1.211:4222"
            - name: REQUESTS_MAX_MESSAGES
              value: "1000"
