--- # postgres
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: sas
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: postgres
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:latest
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/18/docker"
            - name: POSTGRES_PASSWORD
              value: "postgrespwd"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 32Gi

--- # postgres service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sas
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      name: client

--- # postgres external service
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: sas
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      name: client

--- # postgres init container
apiVersion: batch/v1
kind: Job
metadata:
  name: sas-db-init
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: db-init
          image: registry.msvacina.cz/sas_db_init:latest
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgrespwd@postgres-0.postgres:5432/postgres
      restartPolicy: Never
